version: "3"
services:
    albert:
        image: newalbertexpress:latest
        ports:
            - "3000:3000"
        deploy:
            restart_policy:
                condition: on-failure
        extra_hosts:
            - "host.docker.internal:host-gateway"
